package com.github.davidholiday.game;

public enum Action {
    GAME_START,
    GAME_END,
    DEALER_NEXT_ACTION,
    OFFER_CARDS,
    OFFER_CARDS_FOR_DISCARD_TRAY,
    TAKE_CARD,
    DEAL_HAND,
    REQUEST_PLAY,
    OFFER_INSURANCE,
    TAKE_INSURANCE,
    CHECK_FOR_DEALER_BLACKJACK,
    SETTLE_INSURANCE_BETS,
    SURRENDER,
    SPLIT,
    DOUBLE_DOWN,
    HIT,
    STAND,
    REQUEST_WAGER,
    SUBMIT_WAGER,
    ADJUDICATE_GAME,
    OFFER_MONEY,
    TAKE_MONEY,
    CLEAR_HAND,
    NONE
}
