package com.github.davidholiday.game;

public enum Action {
    GAME_START,
    GAME_END,
    DEAL_CARD,
    TAKE_CARD,
    OFFER_INSURANCE,
    TAKE_INSURANCE,
    SURRENDER,
    RESPOND_TO_SURRENDER,
    SPLIT,
    RESPOND_TO_SPLIT,
    DOUBLE_DOWN,
    RESPOND_TO_DOUBLE_DOWN,
    HIT,
    RESPOND_TO_HIT,
    STAND,
    RESPOND_TO_STAND,
    REQUEST_WAGER,
    WAGER,
    SETTLE_WAGER,
    NONE
}
