package com.github.davidholiday.game;

public enum Rules {

    NUMBER_DECKS_USED,
    HIT_SOFT_17,
    DOUBLE_AFTER_SPLIT,
    PLAYER_CAN_DOUBLE_ON_ANY_FIRST_TWO_CARDS,
    PLAYER_CAN_DOUBLE_ON_NINE_ELEVEN_ONLY,
    PLAYER_CAN_DOUBLE_ON_TEN_ELEVEN_ONLY,
    NUMBER_OF_HANDS_PLAYER_CAN_RESPLIT_TO,
    PLAYER_CAN_RESPLIT_ACES,
    PLAYER_CAN_HIT_SPLIT_ACES,
    PLAYER_LOSES_ONLY_ORIGINAL_BET_AGAINST_DEALER_BLACKJACK,
    SURRENDER_RULE,
    BLACKJACK_PAYS_THREE_TO_TWO,
    BLACKJACK_PAYS_SIX_TO_FIVE


}
